# native

#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#  application:
#    name: config-server

server:
  port: 8768

# remote git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhangkexiong/config
          searchPaths: conf
      label: master
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/,http://node2:8761/eureka/,http://node3:8761/eureka/